### ISSUE TITLE
Add support for recursive scan

### ISSUE THREAD

**Issue by genediazjr** [ar4mirez/hapi-handlers#1]
It would be nice if there is a recursive scan of the underlying directories
And allow specifying multiple directories on the the plugin registration

**Comment by ar4mirez** [comment]
Hi @genediazjr thanks for your input we actually are on sync there is copule improvements I'll like to do and one of them is recursive scan using [require-all](http://npm.im/require-all) which also helps excluding, filtering, and some extra sugar.

What you proposing is great would you mind sharing how you are planing to do it ? In that way we can came up with a solution together. 

Thanks.

**Comment by genediazjr** [comment]
My [pull request](https://github.com/ar4mirez/hapi-handlers/pull/2) is based on the [hapi-router](https://github.com/bsiddiqui/hapi-router) lib. It used [glob](https://github.com/isaacs/node-glob) to scan the files. below is now the structure of the options.

``` javascript
{
  includes: 'glob/patter/*.js',
  ignores: 'glob/patter/*.js',
  relativeTo: 'current working dir'
}
```

I'll wait for your approval before I update the README

**Comment by ar4mirez** [comment]
👍  Looks good to me, thanks for your contribution, please go ahead and update the README I'll merge right away.

**Comment by genediazjr** [comment]
Thanks. Updates done.

**Comment by ar4mirez** [comment]
👍  Merged Thank you @genediazjr once again ! this Issue is closed with PR https://github.com/ar4mirez/hapi-handlers/pull/2
